apiVersion: v1
kind: ConfigMap
metadata:
  name: <{CONFIGMAP_NAME}>
  namespace: <{K8S_NAMESPACE_MESH}>
data:
  app_env: dev
  log_level: debug
  concourse_config_directory: /configs-yaml
  concourse_config_filename: config.yaml
  mongodb_schema: deliverymap-svc-2-6-0
  redis_enable: 'true'
  redis_connection_port: '6380'
  redis_connection_tls: 'true'
  enable_swagger: 'true'
  cache_module_enable: 'true'
