GLOBAL_CONFIG:
  GUM_USERNAME: sanitized
  GUM_PASSWORD: sanitized
  GUM_URL: sanitized
  GUM_VALIDATE_USER: sanitized
  GUM_CREATE_USER: sanitized
  API_HOST: sanitized
  UI_HOST: sanitized
  ENV_REGION: AMER
  OPENAM_CLIENT_ID: sanitized
  OPENAM_CLIENT_SECRET: sanitized
  OPENAM_SCOPE: sanitized
  OPENAM_AUTH_ENDPOINT: sanitized
  OPENAM_ACCESS_ENDPOINT: sanitized
  OPENAM_USERINFO_ENDPOINT: sanitized
  OPENAM_LOGOUT_URL: sanitized
  SERVICE_ACCOUNTS_WHITELIST:
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  SERVICE_ACCOUNTS_SUPERUSER_WHITELIST:
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  ALLOW_ACCESS_TOKEN_FOR_SERVICE_ACCOUNTS:
  - sanitized
  - sanitized
  SERVICE_ACCOUNTS_DEALS_WHITELIST: []
  SERVICE_ACCOUNTS_TAX_WHITELIST: []
  SERVICE_ACCOUNTS_CONSULTING_CYBERSECURITY_WHITELIST: []
  TOKEN_LOGOUT_TTL: sanitized
  CC_INTERNAL_SERVICE_ACCOUNT_USER: sanitized
  CC_INTERNAL_SERVICE_ACCOUNT_GRANT_TYPE: sanitized
  CC_INTERNAL_SERVICE_ACCOUNT_CLIENT_ID: sanitized
  CC_INTERNAL_SERVICE_ACCOUNT_SCOPE: sanitized
  CC_INTERNAL_SERVICE_ACCOUNT_AUTH_CHAIN: oauthServiceAccount
  CC_INTERNAL_SERVICE_ACCOUNT_CLIENT_SECRET: sanitized
  CC_INTERNAL_SERVICE_ACCOUNT_PASSWORD: sanitized
  SAME_SITE: 'false'
  AZURE_LOGIN_ACCESS_ENDPOINT: sanitized
  AZURE_LOGIN_CLIENT_ID: sanitized
  AZURE_SCOPE: sanitized
  AZURE_CLIENT_SECRET: sanitized
  AZURE_GRANT_TYPE: authorization_code
  AZURE_STORAGE_ACCOUNT_NAME: sanitized
  AZURE_STORAGE_ACCOUNT_ACCESS_KEY: sanitized
  AZURE_STORAGE_ACCOUNT_CONTAINER_NAME: assets
  AZURE_STORAGE_ACCOUNT_FOLDER_PATH: images
  AZURE_STORAGE_ACCOUNT_SAS_TOKEN: sanitized
  AZURE_COGNITIVE_SEARCH_OCP_SUBSCRIPTION_KEY: sanitized
  AZURE_SUGGESTIONS_ENDPOINT: sanitized
  AZURE_SEARCH_TEXT_ENDPOINT: sanitized
  AZURE_PEOPLESEARCH_ENDPOINT: sanitized
  AZURE_WORKITEMSEARCH_ENDPOINT: sanitized
  MEMORY_HEAP_SIZE: 20*1024
  LDAP_GLBL_USERNAME: sanitized
  LDAP_GLBL_URL: sanitized
  LDAP_GLBL_PASSWORD: sanitized
  LDAP_CONNECTION_TIMEOUT: 10000
  USER_SESSION_TTL: 84600
  ASB_RECEIVER_COUNT: 5
  CONCOURSE_ADMIN_PORTAL_WHITELIST:
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  REDIRECT_WHITELIST:
  - localhost
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - concourse-apps-p-us-dev.azureedge.net
  - concourse-apps-us-dev.azureedge.net
  - concourse-apps-us-qa.azureedge.net
  - concourse-apps-us-uat.azureedge.net
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  ENV_OVERRIDE_KEYS:
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - ENV_REGION
  - sanitized
  - sanitized
  - OPENAM_SCOPE
  - OPENAM_AUTH_ENDPOINT
  - OPENAM_ACCESS_ENDPOINT
  - sanitized
  - sanitized
  - sanitized
  - AZURE_LOGIN_ACCESS_ENDPOINT
  - sanitized
  - AZURE_SCOPE
  - sanitized
  - AZURE_GRANT_TYPE
  - JWT_ALGORITHM
  - JWT_EXPIRE
  - MONGODB_SCHEMA
  - sanitized
  - sanitized
  - MONGODB_PASS
  - MONGODB_CERT
  - MONGODB_SCHEMA_VERSION
  - sanitized
  - sanitized
  - AZURE_STORAGE_ACCOUNT_CONTAINER_NAME
  - AZURE_STORAGE_ACCOUNT_FOLDER_PATH
  - sanitized
  - sanitized
  - AZURE_SUGGESTIONS_ENDPOINT
  - AZURE_SEARCH_TEXT_ENDPOINT
  - EVENTHUB_CONNECTION1
  - EVENTHUB_CONNECTION2
  - sanitized
  - CB_PASS
  - CB_CONN
  - ASB_CONNECTION1
  - ASB_CONNECTION2
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - JIRA_EMAIL
  - FABRIC_PUBLISHING_EVENTHUB_CONNECTION_STRING_CORE
  - FABRIC_PUBLISHING_EVENTHUB_CONNECTION_STRING_ADMIN
  - FABRIC_PUBLISHING_EVENTHUB_NAME_CORE
  - sanitized
  - FABRIC_PUBLISHING_EVENTHUB_TOPIC_CORE
  - FABRIC_PUBLISHING_MUTE_CORE
  - FABRIC_PUBLISHING_EVENTHUB_NAME_ADMIN
  - sanitized
  - FABRIC_PUBLISHING_EVENTHUB_TOPIC_ADMIN
  - FABRIC_PUBLISHING_MUTE_ADMIN
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - APP_VERSION
  - sanitized
  - sanitized
  - sanitized
  - COMMIT_MESSAGE
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - APP_ENV
  - MONGODB_ENV
  - sanitized
  - ENABLE_LAUNCH_DARKLY
  - ENABLE_SWAGGER
  - LOG_LEVEL
  - ENABLE_DEV365_EMAIL_CHECK
  - sanitized
  - sanitized
  - sanitized
  - LDAP_CONNECTION_TIMEOUT
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - MICROSOFT_SHAREPOINT_TENANT
  - MICROSOFT_GRAPH_API_RESOURCE
  - sanitized
  - REDIS_CLUSTER_ENABLE
  - sanitized
  - REDIS_CONNECTION_PORT
  - REDIS_CONNECTION_PASS
  - REDIS_CONNECTION_TLS
  - ENABLE_JWT_AUTH
  - ENABLE_AUTH_COOKIE
  - REDIS_ENABLE
  - REDIS_CONFIG_RETRY_INTERVAL
  - REDIS_MAX_RETRIES
  - REDIS_RETRY_EXPONENTIAL
  - USER_SESSION_TTL
  - DATA_DOG_MODULES
  - sanitized
  - COUCHBASE_CA_CERT
  - sanitized
  - COUCHBASE_CERT
  - sanitized
  - sanitized
  - COUCHBASE_DEFAULT_BUCKET
  - COUCHBASE_ARCHIVE_BUCKET
  - sanitized
  - sanitized
  - sanitized
  - sanitized
  - ASB_RECEIVER_COUNT
  - sanitized
  - USER_ENGAGEMENT_BATCH_SIZE
  - sanitized
  APP_ID: sanitized
  APP_VERSION: ''
  BUILD_URI: sanitized
  DATA_DOG_MODULES: null
  DEFINITION_ID: sanitized
  COMMIT_ID: sanitized
  COMMIT_MESSAGE: ''
  MONGODB_USER: sanitized
  MONGODB_SCHEMA_VERSION: 0-018
  MONGODB_SCHEMA_BASE_NAME: concourse
  MONGODB_ENV: dev
  MONGODB_URI: sanitized
  MONGODB_ENABLE_VIEW_CREATE: false
  MONGODB_MAX_POOL_SIZE: 100
  MONGODB_MIN_POOL_SIZE: 0
  LOG_LEVEL: debug
  LOG_LEVELS:
  - log
  - error
  - warn
  - debug
  APP_ENV: dev
  DEFAULT_VERSION: '3'
  SERVICE_PORT: 5018
  SERVICE_TCP_PORT: 5019
  SERVICE_TCP_LISTEN_ADDR: 0.0.0.0
  ENABLE_INTERNAL_API: true
  ENABLE_JWT_AUTH: true
  ENABLE_AUTH_COOKIE: true
  JWT_KEY: sanitized
  JWT_ALGORITHM: RS256
  JWT_EXPIRE: 500
  JWT_BASE64: true
  REDIS_CLUSTER_ENABLE: false
  REDIS_CONNECTION_HOST: sanitized
  REDIS_CONNECTION_PORT: 6379
  REDIS_CONNECTION_PASS: ''
  REDIS_CONNECTION_TLS: true
  REDIS_ENABLE: false
  REDIS_CONFIG_RETRY_INTERVAL: 60
  REDIS_MAX_RETRIES: 5
  REDIS_RETRY_EXPONENTIAL: 2
  EVENTHUB_CONNECTION1: ''
  EVENTHUB_CONNECTION2: ''
  EVENTHUB_NAME: microservice-eh
  ENABLE_EVENTHUB_TRANSPORT: false
  ENABLE_EVENTHUB_CLIENT: false
  ENABLE_EVENTHUB_TEST: false
  ASB_CONNECTION1: ''
  ASB_CONNECTION2: ''
  ENABLE_ASB_TRANSPORT: false
  ENABLE_ASB_CLIENT: false
  ENABLE_TCP_TRANSPORT: true
  MICROSOFT_SHAREPOINT_CLIENT_ID: sanitized
  MICROSOFT_SHAREPOINT_USERNAME: sanitized
  MICROSOFT_SHAREPOINT_PASSWORD: sanitized
  MICROSOFT_SHAREPOINT_CLIENT_SECRET: sanitized
  MICROSOFT_SHAREPOINT_TOKEN_PATH: sanitized
  MICROSOFT_SHAREPOINT_TENANT: devpwc365.sharepoint.com
  MICROSOFT_SHAREPOINT_EDITROLE: 1073741830
  ENABLE_DEV365_EMAIL_CHECK: true
  FABRIC_PUBLISHING_EVENTHUB_CONNECTION_STRING_CORE: null
  FABRIC_PUBLISHING_EVENTHUB_CONNECTION_STRING_ADMIN: null
  FABRIC_PUBLISHING_EVENTHUB_NAME_CORE: eh-07
  FABRIC_PUBLISHING_CLIENT_ID_CORE: sanitized
  FABRIC_PUBLISHING_EVENTHUB_TOPIC_CORE: Concourse
  FABRIC_PUBLISHING_MUTE_CORE: 'false'
  FABRIC_PUBLISHING_EVENTHUB_NAME_ADMIN: eh-05
  FABRIC_PUBLISHING_CLIENT_ID_ADMIN: sanitized
  FABRIC_PUBLISHING_EVENTHUB_TOPIC_ADMIN: ConcourseAdmin-Dev
  FABRIC_PUBLISHING_MUTE_ADMIN: 'false'
  IN_APP_NOTIFICATION_URL: sanitized
  IN_APP_NOTIFICATION_DELAY: 10000
  IN_APP_NOTIFICATION_TOKEN_PATH: sanitized
  IN_APP_NOTIFICATION_TIMEOUT: 15000
  ADOPTION_SERVICE_ACCOUNT_USERNAME: sanitized
  ADOPTION_SERVICE_ACCOUNT_PASSWORD: sanitized
  ADOPTION_SERVICE_ACCOUNT_V2_USERNAME: sanitized
  ADOPTION_SERVICE_ACCOUNT_V2_PASSWORD: sanitized
  ID_BROKER_HOST: sanitized
  ASB_LOCK_TOKEN: sanitized
  ASB_TOKEN_PUBLIC_KEY: sanitized
  EVENTHUB_LOCK_TOKEN: sanitized
  EVENTHUB_TOKEN_PUBLIC_KEY: sanitized
  JIRA_HOST: sanitized
  JIRA_PASSWORD: sanitized
  JIRA_EMAIL: sanitized
  LAUNCH_DARKLY_SDK_KEY: sanitized
  ENABLE_LAUNCH_DARKLY: false
  ENABLE_SWAGGER: true
  ENABLE_REST_RPC_BRIDGE: sanitized
  SURVEY_CLIENT_ID: sanitized
  SURVEY_CLIENT_SECRET: sanitized
  SURVEY_BASE_URL: sanitized
  SURVEY_TOKEN_URL: sanitized
  SURVEY_LISTEN_CLIENT_ID: sanitized
  ENABLE_USER_SESSION: sanitized
  FABRIC_PUBLISHING_DATA_VERSION: '2'
  ASB_PUB_TOPIC: microservice-pub2<{ASB_QUEUE_SUFFIX}>
  RAID_PUB_SUB_PRIMARY_SUBSCRIBER_KEY: sanitized
  DELIVERABLES_PUB_SUB_PRIMARY_SUBSCRIBER_KEY: sanitized
  DELIVERY_MAP_PUB_SUB_PRIMARY_SUBSCRIBER_KEY: sanitized
  ENGAGEMENT_PUB_SUB_PRIMARY_SUBSCRIBER_KEY: sanitized
  REDIS_NAMESPACE_KEY: sanitized
  FEATURE_ROLES_PERMISSIONS_KEY: sanitized
  REDIS_UNAUTH_USER_PREFIX: sanitized
DELIVERY_MAP_SERVICE:
  ENABLE_ASB_CLIENT: true
  ENABLE_ASB_TRANSPORT: true
  INHERIT_GLOBAL: true
  REDIS_NAMESPACE_KEY: sanitized
  SERVICE_HOST: sanitized
  SWAGGER_URI: sanitized
  BLOB_STORAGE_ACCOUNT_NAME: sanitized
  BLOB_STORAGE_CONTAINER_NAME: ''
  BLOB_STORAGE_FOLDER_PATH: ''
  BLOB_STORAGE_SAS_TOKEN: sanitized
  TRANSLATOR_URL: sanitized
  TRANSLATOR_API_KEY: sanitized
  MONGODB_COLLECTION: deliverymaps
  DELIVERY_MAP_DIGITAL_ASSETS_AGGREGATOR: vw-deliverymaps-digitalassets
  TERRITORY_COLLECTION: Territories
  WORK_ITEM_CONFIGS_COLLECTION: WorkItemConfigs
  WORK_PLAN_CONFIGS_COLLECTION: WorkPlanConfigs
  BUSINESS_CONSULTING_AREAS_COLLECTION: BusinessConsultingAreas
  BXT_ACTIONS_COLLECTION: BxtActions
  PDM_STAGE_CONFIG_COLLECTION: PDMConfigs
  PDM_ATTRIBUTE_CONFIG_COLLECTION: PDMAttributeConfigs
  PDM_ORDER_CONFIG_COLLECTION: PDMOrderConfigs
  ENABLE_WORK_ITEM_CONFIGS_AUDIT: true
  ENABLE_WORK_PLAN_CONFIGS_AUDIT: true
  ENABLE_BUSINESS_CONSULTING_AREAS_AUDIT: true
  ENABLE_BXT_ACTIONS_AUDIT: true
  ENABLE_PDM_STAGE_CONFIGS_AUDIT: true
  ENABLE_PDM_ATTRIBUTE_CONFIGS_AUDIT: true
  ENABLE_PDM_ORDER_CONFIGS_AUDIT: true
  ENABLE_TERRITORIES_AUDIT: true
  MONGODB_VIEW_CONFIG_DIRECTORY: /app/views
  MONGODB_VIEW_DEFINITIONS:
  - name: vw-deliverymaps-children
    filename: vw-deliverymaps-children.json
  - name: vw-deliverymaps-digitalassets
    filename: vw-deliverymaps-digitalassets.json
  ENABLE_USER_PROFILE_API: sanitized
  GRAPHQL_PLAYGROUND: true
  GRAPHQL_INTROSPECTION: true
  ENV_OVERRIDE_KEYS:
  - MONGODB_SCHEMA_VERSION
  - GRAPHQL_PLAYGROUND
  - GRAPHQL_INTROSPECTION
  - sanitized
  - BLOB_STORAGE_CONTAINER_NAME
  - BLOB_STORAGE_FOLDER_PATH
  - sanitized
  - sanitized
  - sanitized
