apiVersion: v1
kind: ConfigMap
metadata:
  name: <{CONFIGMAP_NAME}>
  namespace: <{K8S_NAMESPACE_MESH}>
data:
  app_env: dev
  dd_profiling_enabled: 'true'
  dd_profiling_timeline_enabled: '1'
  dd_trace_debug: 'false'
  dd_trace_startup_logs: 'false'
  log_level: debug
