apiVersion: apps/v1
kind: Deployment
metadata:
  name: <{DEPLOYMENT_NAME}>
  namespace: <{K8S_NAMESPACE_MESH}>
spec:
  replicas: <{REPLICAS}>
  selector:
    matchLabels:
      tags.datadoghq.com/service: <{SERVICE_NAME}>
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: <{ver}>
        tags.datadoghq.com/service: <{SERVICE_NAME}>
        release: <{RELEASE_LABEL}>
    spec:
      imagePullSecrets: []
      initContainers: []
      volumes:
      - name: config-yaml
        configMap:
          name: <{CONFIGMAP_YAML_NAME}>
      containers:
      - name: <{SERVICE_NAME}>
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 600Mi
          limits:
            cpu: '5'
            memory: 3Gi
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - name: config-yaml
          mountPath: /configs-yaml
          readOnly: true
        env:
        - name: NODE_OPTIONS
          value: --max-old-space-size=3072
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: app_env
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: log_level
        - name: CONCOURSE_CONFIG_DIRECTORY
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: concourse_config_directory
        - name: CONCOURSE_CONFIG_FILENAME
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: concourse_config_filename
        - name: MONGODB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: mongodb_schema
        - name: MONGODB_PASS
          value: "dummy"
        - name: MONGODB_CERT
          value: "dummy"
        - name: REDIS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: redis_enable
        - name: REDIS_CONNECTION_PORT
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: redis_connection_port
        - name: REDIS_CONNECTION_TLS
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: redis_connection_tls
        - name: REDIS_CONNECTION_PASS
          value: "dummy"
        - name: ENABLE_SWAGGER
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: enable_swagger
        - name: CACHE_MODULE_ENABLE
          valueFrom:
            configMapKeyRef:
              name: <{CONFIGMAP_NAME}>
              key: cache_module_enable
