name: Deploy Microservice

run-name: All Environments - ${{ github.ref_name }}

on:
  push:
    branches:
      - changestogithubworkflow
  workflow_dispatch:
    inputs:
      ASB_QUEUE_SUFFIX:
        description: 'ASB Queue Suffix'
        required: true
        type: choice
        default: ' '
        options:
          - ' '
          - '-2'

      EVENTHUB_CONSUMER_GROUP:
        description: 'EventHub Consumer Group'
        required: true
        type: choice
        default: ConsumerGroup1
        options:
          - ConsumerGroup1
          - ConsumerGroup2

      RELEASE_LABEL:
        description: 'Release label'
        required: false
        type: string
        default: 'stable'

      promoteFromDev:
        description: 'Promote versions from Dev?'
        required: false
        type: boolean
        default: false

      RESTART_PODS:
        description: 'Restart pods after deploy?'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  us-dev:
    name: us-dev
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: us-dev
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  us-qa:
    name: us-qa
    needs: us-dev
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: us-qa
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  us-perf:
    name: us-perf
    needs: us-qa
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: us-perf
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  us-int:
    name: us-int
    needs: us-perf
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: us-int
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  us-stage:
    name: us-stage
    needs: us-int
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: us-stage
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  us-prod:
    name: us-prod
    needs: us-stage
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: us-prod
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  us-prod-dr:
    name: us-prod-dr
    needs: us-prod
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: us-prod-dr
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  emea-stage:
    name: emea-stage
    needs: us-prod-dr
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: emea-stage
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  emea-prod:
    name: emea-prod
    needs: emea-stage
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: emea-prod
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  emea-prod-dr:
    name: emea-prod-dr
    needs: emea-prod
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: emea-prod-dr
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  apac-stage:
    name: apac-stage
    needs: emea-prod-dr
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: apac-stage
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  apac-prod:
    name: apac-prod
    needs: apac-stage
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: apac-prod
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit

  apac-prod-dr:
    name: apac-prod-dr
    needs: apac-prod
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: apac-prod-dr
      ASB_QUEUE_SUFFIX: ${{ inputs.ASB_QUEUE_SUFFIX || ' ' }}
      EVENTHUB_CONSUMER_GROUP: ${{ inputs.EVENTHUB_CONSUMER_GROUP || 'ConsumerGroup1' }}
      RELEASE_LABEL: ${{ inputs.RELEASE_LABEL || 'stable' }}
      promoteFromDev: ${{ inputs.promoteFromDev || false }}
      RESTART_PODS: ${{ inputs.RESTART_PODS || false }}
    secrets: inherit